name: Daily Check-in

on:
  schedule:
    # 每天的 10:33 UTC 时间执行
    - cron: "33 10 * * *"
  push:
    # 当推送到 main 或 feature 分支时触发
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main
jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.5"

      - name: Install dependencies
        run: go mod download

      - name: Run Check-in
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          A_TEST_NUMBER: ${{ secrets.A_TEST_NUMBER }}
        run: |
          # 生成一个 1 到 10 分钟的随机延迟
          # DELAY=$((RANDOM % 10 + 1))
          # echo "Sleeping for $DELAY minutes..."
          # sleep "${DELAY}m"
          go run main.go
